name: Auto-Sync Forex Factory Calendar

# Kapan aksi ini dijalankan?
on:
  schedule:
    # Menjalankan script setiap hari Minggu jam 22:00 UTC (Senin 05:00 WIB pagi)
    - cron: '0 22 * * 0' 
  workflow_dispatch: # Memungkinkan Anda menekan tombol "Run" manual kapan saja

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script (Fetch News)
      run: python fetch_news.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ff_calendar_thisweek.csv
        # Jika tidak ada perubahan, git commit akan error, jadi kita pakai || true
        git commit -m "Auto-update High Impact News [Sunday Sync]" || true
        git pushv
